[project]
name = "qwen-vl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.109.1",
    "opencv-python>=4.12.0.88",
]
